### ISSUE TITLE
Installation guide

### ISSUE THREAD

**Issue by shabeebpm** [mf1d3l/Splunk4DFIR#17]
Could you please share the complete installation guide?

**Comment by mf1d3l** [comment]
Hello shabeepm,

what are you missing from the readme ? The [how-to](https://github.com/mf1d3l/Splunk4DFIR?tab=readme-ov-file#how-to) section should be enough to get you started. The only requirement is for you to have docker installed. Building and running the container after having dropped your case files in the proper path is all you need to do.

**Comment by shabeebpm** [comment]
Thank you for your response, I am getting below error message related to docker file,
ERROR: failed to solve: failed to read dockerfile: open Dockerfile: no such file or directory

**Comment by mf1d3l** [comment]
that error message would typically occur if there is no Dockerfile found in your current working directory, are you running the docker build command from within the base directory of the project ?

```shell
git clone https://github.com/mf1d3l/Splunk4DFIR.git
cd Splunk4DFIR/
sudo docker build -t splunk4dfir .
```

**Comment by shabeebpm** [comment]
Thank you very much, the error was related to docker and i tried to manage it and installed Splunk4DFIR, however now it is stuck in the stage, which says '_Ansible playbook complete, will begin streaming splunkd_stderr.log_', below is the screenshot

![Screenshot 2024-11-13 112738](https://github.com/user-attachments/assets/5f45fd29-b47f-4f9c-a79f-8a9b77f7440d)

**Comment by mf1d3l** [comment]
you can login as admin user with the password set via the `SPLUNK_PASSWORD` variable passed via the docker run command

**Comment by shabeebpm** [comment]
Thank you very much, 
One last question - I am using this docker on my Ubuntu WSL and once it is restarted, how can I run splunk4dfir docker again ?

**Comment by mf1d3l** [comment]
> Thank you very much, One last question - I am using this docker on my Ubuntu WSL and once it is restarted, how can I run splunk4dfir docker again ?

you can manage the instance with the docker start/docker stop commands

> Could you please advise under which directory, I can create the folder, artifacts/ ?

you can just use the folder structure of the project or you can map /mnt/artifacts to any arbitrary path where you case files are located using the -v volume flag of the docker run command

if you are completely new to docker I recommend you read the docker cli documentation and get familiar with the basics: https://docs.docker.com/reference/cli/docker/

**Comment by shabeebpm** [comment]
Thank you very much for your support, I am not familiar with docker and facing few issues, (sorry for bothering you)
so when Ib tried to run the splunk4dfir container using the command below, i am getting below error message

![image](https://github.com/user-attachments/assets/94fdb9bd-daee-4ff2-81fb-7bb90a05bfa2)

**Comment by mf1d3l** [comment]
> Could you please share the correct command to run this docker in the background ?

it's right there in the how-to: https://github.com/mf1d3l/Splunk4DFIR?tab=readme-ov-file#how-to

```
sudo docker run --name splunk4dfir -e SPLUNK_START_ARGS=--accept-license -e SPLUNK_PASSWORD=changeme -e SPLUNK_APPS_URL="/mnt/resources/sankey-diagram-custom-visualization_130.tgz" -p 8000:8000 -p 8089:8089 -v ./artifacts:/mnt/artifacts -v ./resources:/mnt/resources splunk4dfir:latest start
```

**Comment by shabeebpm** [comment]
I tried to run the same command, but i am getting below error - 

![image](https://github.com/user-attachments/assets/5e27e06c-e8d2-41e9-9007-b6003862b283)

**Comment by mf1d3l** [comment]
thats because you already have a container created with the name "splunk4dfir" 

you can delete it with `sudo docker rm splunk4dfir` then run the docker run command again. 

once the container instantiated via the docker run command you can stop it with `sudo docker stop splunk4dfir` and start it again with `sudo docker start splunk4dfir`

 Getting familair with the basics of docker container management is essential if you want to use this project.

**Comment by shabeebpm** [comment]
It is working well, thank you for your support
